services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sales-api
    ports:
      - "8000:8000"
    environment:
      APP_NAME: Sales API
      SQLITE_URL: sqlite:///./data/sales.db
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB_NAME: sales_db
      MONGO_COLLECTION_NAME: sale_texts
    volumes:
      - ./data:/app/data
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: sales-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:

